apiVersion: apps/v1
kind: Deployment
metadata:
  name: caller-app
  namespace: default  # Explicit for clarity or Omit and specify via kubectl -n default
spec:
  replicas: 1 # Increase to 2-3 for production
  selector:
    matchLabels:
      app: caller-app
  template:
    metadata:
      labels:
        app: caller-app
      annotations: 
        dapr.io/enabled: "true"
        dapr.io/app-id: "caller-app"
        dapr.io/app-port: "8000"
        dapr.io/log-level: "info"
    spec:
      containers:
      - name: app
        image: caller-app # CORRECTED: Match the Tiltfile ref
        imagePullPolicy: IfNotPresent
        ports:
          - containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: caller-app-service
  namespace: default
  labels:
    app: caller-app
spec: 
  selector:
    app: caller-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
      appProtocol: http
  type: ClusterIP